version: '3'

services:
  mongo:
    restart: always
    build:
      context: db
      dockerfile: Dockerfile
    command: sudo docker build . 
    ports:
      - '27017:27017'
  twitterman-backend:
    depends_on:
      - 'mongo'
    build:
      context: twitterman-backend
      dockerfile: Dockerfile
    command: sudo docker build . 
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=mongodb://mongo:27017
