FROM mongo:3.4.1

WORKDIR /build
COPY . .
#RUN mongod &
#RUN mongoimport --db twitterman --collection Tweets --file json/tweets-data.json --jsonArray
#RUN mongoimport --db twitterman --collection Users --file json/user-data.json --jsonArray